(function (lib, img, cjs) {

var p; // shortcut to reference prototypes

// stage content:
(lib.exit = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.jakechairexit();
	this.instance.setTransform(264.3,217.5,1,1,0,0,0,264.3,217.5);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-22.4,95.1,291.1,339.9);


// symbols:
(lib.glaptop = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("AFTmIIs+gIAoImDINQABAFUmIIAAAAAFTmIIABAAAlDGHIjFsKAIJGRIjBsT");
	this.shape.setTransform(52.2,40.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(1,1,1).p("AC2mCIALgGAp9mQIgdANADCmIIAAAAIAAAAIC8MBQCRgeCMgUIAAAPIj8ArIAAAAIgUAIIgUAIItJAAIgDgKADCmIIgBAAAF+F5IANAQ");
	this.shape_1.setTransform(66.8,40.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#F7F7F7").s().p("AF3GRIjBsTIDBMTItJAAIgDgKIjFsKINQABIALgGIABAAIC8MBQCRgeCMgUIAAAPIj7ArIAAAAIgVAIIgNgQIANAQIgUAIgAGLGJgAqamDIAdgNIM+AIIgLAGgADBmIg");
	this.shape_2.setTransform(66.8,40.4);

	this.addChild(this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0.2,133.5,80.4);


(lib.gjakeexitfloor = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("AWvkDImGIHMgnXAAAIJsoHg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("A2uEEIJsoHMAjxAAAImHIHg");

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-145.5,-25.9,291.1,52);


(lib.gdesk = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("APHsIIAACuIAAVEIAAAZAP0iiIAApmAKbnpIAAkYAKbh6IAANWIAAAtAKci/IgBigIAAiKAP0MAIAAgWIAAuMAvzMJIAAgDIAAgqIAAwZAvzsBIAAHEAvzMGIAxgZIAAgR");
	this.shape.setTransform(132.9,89.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(1,1,1).p("AQBs+IgOgEMgiGAAAQgRAAgNASQgMASAAAaQAAAKACAKQADAMAHALQANASARAAIA7AAIDXAAIaOAAIDXAAIAPAAQAFAAAEgCQAFgBADgDAQarwQACgKAAgKQAAgagMgSQgHgJgIgFQgCgBgDgBQgEgCgFAAAS3rXQAVgUgogeIijg1ASTrNIAUAAQAKgFAGgFAQarwQgDAMgHALQgGAHgGAFIA1AAIAtAAIAtAAAPklJIAAl+AMOiEIgBBEAMNNDIDXAAIAAyMASTk6IAAmTAQ5M9IhQAGARmMkIgtAAASTk6IAARxIgrADIgCAAAxYjcQAAj1AAj2AxYjcQAAClAACjIAAJ8IAABbIDXAAAtQMWIgxAAAxYBsQgTEzATFJAtQMWIZdAA");
	this.shape_1.setTransform(121.5,83.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#7B5F5B").s().p("AQ8hyIAAiuIAACuQhMAQgJDFIAAl8IAAF8Qgsj8hIgkQgtBfgZB1QgMgMgRgMIAAkYIAAEYQgVgRgcgTQi+h+qThFQqUhFh4HWIAAnCIaOAAIDXAAIAOAAQAFgBAFgBIAIgFIgIAFQgFABgFABIgOAAIjXAAI6OAAIjXAAIg7AAQgRgBgNgSQgHgKgDgNMAjVAAAICcAZQgFAGgKAEIgUAAIgtAAIgtAAIg1AAQAGgEAFgIQAIgKADgNQgDANgIAKQgFAIgGAEIA1AAIAtAAIAtAAIAAGSQglAwgICiIAApkIAAJkQgNkWggiggAMQCHIAMgEQgKBOgCBWgAxVkZIDXAAIAAHCQgLlGhUhHQhhC4gXD8IAAnpgAPnBjg");
	this.shape_2.setTransform(121.2,40.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#8F827F").s().p("APkNDIAAyMQAJjGBMgRQAgCiANEWQAJihAkgxIAARxIgrADIgCAAIAAgWIgtAAIAA1EIAAVEIAAAZIhQAGgARmMkIAAuMgAMNNDIAAgtIAAtWIABhEQAChXAJhOIgMAFIAAiKIAACKIABCgIgBBEIAANWI5dAAIgxAAIAAwZQB4nYKVBGQKSBFC+B+QAcATAVARQARAOAMAMQAZh3AthgQBIAlAsD9IAASMgAxYNDIAAhbQgTlJATkzQgNivANiZQAXj9Bhi5QBUBHALFIIAAQZIAAAqIAAADgAxYBsIAAJ8IAAp8IAAlIIAAFIgAuBMWIAxAAIAAARIgxAZgAuBMWgAMNkkgAQarwQACgKAAgKQAAgagMgSQgHgJgIgFICjA1QAoAegVAUgAy7rwQgCgKAAgKQAAgaAMgSQANgSARAAMAiGAAAIAOAEQAIAFAHAJQAMASAAAaQAAAKgCAKgAQBs+g");
	this.shape_3.setTransform(121.5,83.5);

	this.addChild(this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,243,167.1);


(lib.gchair = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("AlxhSQDhnGiCmdQA1hQBUgPQF8hKGOBlQA4gBAlBMQkTIIDdFUAKwhGQAAAAAAAAQAAAAAAAAQAiAmgjArIAAM1IgqAtIg3AAIAAscIiMBmIAANaIgoAkIhkAAIAAthIpvAAIAAJ8IgZAhIg3gBIAAqcIjNAAIAAMvIgoAyIhVAAIAAthQgTgcATgbQAUgGAUgHQCTg1CiihIAAAAIAAAAArTDUIBVAAIAoAAArTCdQAUADAUACQIgBMIlhbQC9guBZirAmJDUIA3AAIAZAAAJOBRIA3gnIAqgfAGaDUIhkAAAGaDUIAogdAGaCTQAZAggZAhIAANhAKFAqIAANDAlSDUIAAKdAp+DUIAANh");
	this.shape.setTransform(73.4,110.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(1,1,1).p("AoSAFIAAAAQADgFACgEAINgEQADAEADAFIwlAA");
	this.shape_1.setTransform(89,102.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#663300").s().p("AFIIUIAAtfIBlAAIAANfgAGtlLIAogdIAANZIgoAjgArBIUIAAtfIBVAAIAANfIAAtfIAoAAIAAMuIgoAxgAlAFQgAl3FQIAAqbIA3AAIAZAAIAAJ7IgZAgIAAqbIAAKbgAKYFMgAJhFMIAAsZIA3goIAqgeIAAMyIgqAtIAAtBIAANBgApslLg");
	this.shape_2.setTransform(71.6,165.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#15212D").s().p("AGaKEIAAAAgAE2KEIpvAAIgZAAIg3AAIjNAAIgoAAIhVAAQgTgbATgcQAUgFAUgHQCTg2CiiiIAAAAIAAAAIAAAAIAFgMIQZAAIAHAMIABAAQhZCsi9AuIgKACIgMACQkiAukfAAIAAAAIAAAAQjxAAjwggIgNgCIgogGIAoAGIANACQDwAgDxAAIAAAAIAAAAQEfAAEiguIAMgCIAKgCQC9guBZisIAAAAQAiAmgjAtIgqAeIg3AoIiMBlIgoAdQAMgQAAgQQAAgRgMgQQAMAQAAARQAAAQgMAQgAKvFpIwlAAgAlxFdQDhnFiCmcQA1hRBUgPQF8hKGOBlQA4gBAlBNQkTIGDdFUg");
	this.shape_3.setTransform(73.4,67.4);

	this.addChild(this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,3,146.9,215.4);


(lib.gjakeexittween = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.gdesk("synched",0);
	this.instance.setTransform(2.5,78.9,1,1,0,0,0,121.5,83.5);

	this.instance_1 = new lib.glaptop("synched",0);
	this.instance_1.setTransform(-47.4,-41.2,0.993,1.031,0,14,1.7,66.8,40.2);

	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("AQpEEMgnXAAAIJsoHMAjxAAAg");
	this.shape.setTransform(3.5,150.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("A2uEDIJsoGMAjxAAAImGIGg");
	this.shape_1.setTransform(3.5,150.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape},{t:this.instance_1},{t:this.instance}]}).wait(40));

	// Layer 3
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#35301C").ss(1,1,1,3,true).p("ADnkKQAEAWgEAYQAAAAAAAAAjoCLQABAAABABAiCg3QABgBABgCQAEgRABgRAClD7QACADACADQAEAFAEAFACbDuQAFAHAFAG");
	this.shape_2.setTransform(27.3,-28.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#000000").ss(1,1,1).p("ACGl9IA/AHQAcAPA0AyQgFADgFACQgGADAJABQAZATA9BAQBXBcA0BTQBSCEAUBgQAIAnAHAdQAHAdAGAVQgNAHgPAHQAIApAMDAIgyAAIjCAAQAAADgBADAiMp7QgEAPACAKQAFAOALgCQALgDgEgYQAAgEgCgEAB5l5IANgEAEOksQgQADgRAaQgQAagaAeQgZAfgrA2QAAAAAAAAQAAAAgBgBQAAgCgBgCQgWgxgmgnQgMgLgIgIQgBgBAAAAIAAAAQgBgBgBgBQgMgNgGgHQAGAMAFALQAPAkAKAmQABACAAACQAGAXAFAZQABAFAAAFQAOBNACA8QABALAAAKQAAANgBANQAAAZgBAYQgBAigCAgIAAABQgEA1gGAvQAAACAAACQgFAggFAdAE5DjQgGgVgHgWQgNgmgPgoQgIgVgnhVACWlYQAAAAABgBQgFgFgEgGACLlnIACADIABAAAhdi3QgCAWgDAdQAAABAAAAQAAABABAAQAyAXBXAAIAfgJIABAAAAXkKIAAAAQABAAAAABQAAgBgBAAIAQARQACADADADACWlYQg0AhhLAtAB/iCQAAAAgBgBADFl2QgUANgaAQAhlkuQACADACADQAFAIADAKQACAKAAAMQAAALgGA8QAAABAAABAhZkWQgYAZgtAOQglALgPAKAjSjaQAOAoAPA+IAAAAQAMAKAAgBQAKgNASgWQAegiASgHAjkiSQgGAUgJAVQgNAdgJAQIAAAAQgFAJgEAEQAHgEAGgEQAygiAbgYQACgBABgCAjkiSIAAAAQANgmAFgiAkhhNQAPgUASgTQANgPAPgPAkhhNQg5BLgUBLQgLArgGA/QgDAjgFBNIAAAdQAAAFAAAGQABAPABAUQABAWABAdQAAAFABAFQAEAGAIAFAkQDzQAEgSAEgTQAJg1AGg8IgCgyAiwhhQgBgEgBgFQgBgEgBgEQAAgBgBgBQAHAQgCADQADAUADAVQAIBDgDBMQgEAPgMBVQgEAYgDAXQgMBMgLA3QAAABgBAAQgCAKgCAJAhkInIBwAAIABAAIgBgCQAAgFABgGQADgPAIgXQASg1AJgdQAHgcAHgfAlBGUQgIAVgMAdQgDAIgEAJQgOAngKApIBoAAQAOgfAPgsQALgeAMg9AlBGUQAFgMADgJIABgBQAYg9AQhOAmCGrQgDgEgBgEQAAAAgBgBQAAAAAAgBQgFgPhzBUQg3Apg6AgICcgFIBggDQgDAQgEARAloG+QgDgBgEgCQgCgCgDgBAloG+QAMAHAHABAkMInQgGAOgFALQgKAVgKAnAkMInICoAAAE5DjQAPAyAKAuIAAAAQANAJARAIQANAHAQAGQAkANAWAAQBBgRAtgRQARgHAPgHAANInIAHAIAAXInIgKAAAAXInIFeAAQAKg3gDg1QgEhDgIgk");
	this.shape_3.setTransform(41.5,-58.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#35301C").ss(1,1,1).p("ABuAOQgogMgVgCQgRgDgOAHAhsAGQATgQAagD");
	this.shape_4.setTransform(23.8,-126.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f().s("#000000").ss(1,1,1).p("AjlAeQgcglgLgwQgLguADgwQABgiALgfQAIgZASgUQAJgKAOgDQAmg9BFgVQAUgHAUgHQAcgHAcAAQBUABBPAhQAPAHAOAIQAcARAUAXQAWAZAMAeQARAtgCAxQAAAVgBAVQgBAbgEAaQgIA4gYA0QgKAVgIAWQgPAsgLAsQgEARAAASQABAXAFAYQAAABAAACQACAIAAAJIADACAghggQgkgRghgVQgmgZgggeQgIgGgHgHQgWAlgLAqQgGAYgDAZIAAABQgBASABAVQAAAggFAfQgHAyAJAuQAJAvAZArQAVAjAbAeQANAOARAKQAXANAbgJQARgFAPgJQAEgCADgDQANgHAMgIQAGgFAGgEAgZgqQAiAdApANIgUgaIgFgEAghggIgSgjQANAOANALAjkjIQAMAZARAVQAGAIAGAIIAEgGAitAhQAAADAAADQAAAJgDAHQgCAGgEAAQgDAAgDgGQgCgHAAgJQAAgDAAgDQABgDAAgDQABgCAAgBQADgHADAAQAEAAACAHQABABABACQAAADABADgACZB7QAAAAAAAAIABACQANguARgtQACgIABgIQACgLADgJQAGgXgFgVQgDgLgKgEQgPAEgLANQgXAfgUAdIg0gaAh3CxQgagBgVgMQgOgJAJgPQAJgPAOgYQANgXABgyAgIDXQgnAHgmAHQgqAGgpAHAg6AaQgEgPgKACQgDAGgCAFAAegaIAaAOIADACACaB9QABADAAADQADAOgCAPQgFAygMAvIAdgVIgBAkIAAASIARgIACZB7QgBADAAAEQgBAAAAABIADgGACSCdQgIAegQAcQgQAegZAXQgjAjgoAaACSCdQADgNACgNADHErIgPgR");
	this.shape_5.setTransform(35.2,-124.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#284360").s().p("AgkEwIAQgSQAVgZAVgcIAAAAIABgBIgIgGQgegcgjgXQgagSgdgKQgRgGgTgBIgKgCIADgSIABgDQALg2AMhKIAHguQANhWAEgPQAChMgIhFQASAxACAoQADAtgEAtQgCAZgGAZIgBAEIAAADQAFAWATAIQAQgEARABQAnABAsgDQAngDBCgHQgLABAGhDIAIAAIgDBCIAAAAQgDA0gHAvIAAAEQgFAggFAdQgGAfgIAbQgIAegTA0QgIAYgDAPIgBALIAAACg");
	this.shape_6.setTransform(35,-33.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FDF9E8").s().p("AgPAHIAIgFIAWgNIAAABIgaAWIgEgFg");
	this.shape_7.setTransform(32.8,-89.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#3A5F87").s().p("AiyFwQANggAQgsQALgeAMg9IAKACQATACARAFQAdAKAaASQAiAYAgAcIAHAGIAAAAIAAABQgVAbgXAaIgPASgAhHgEIABgDIABgEQAFgZADgYQAEgugDgsQgCgogTgxIgGgpQADgEgHgPIAMAJIAcgkQAdghASgHIgFAzIAAABIACABQAvAWBZAAIAfgIIADAJQAOBOACA+IAAAVIAAAaIgBAwIgIAAQgGBCALgBQhCAHgoADQgsADgmgCQgRAAgRAEQgSgJgGgUgACvAKIAAAAIAAAAg");
	this.shape_8.setTransform(32.5,-40.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#B9A77B").s().p("Ai3DZQgBARgFARIgBAEIAHgmgACrBAIAAgVQAEAWgEAYIAAABIAAgagAi3gxIAAAAIAAAAIgZgRQAPgTASgUIAdgeQgHAUgJAVQgMAegJAPIADAFIgMAIQAEgEAFgJgADQh3IABAAIgBABIAAgBgABpj+IATAVIgIADIgLgYg");
	this.shape_9.setTransform(33.3,-59.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#968150").s().p("AhlGOIgKgNQADgOAIgYQATg1AIgdQAIgcAGgfIAoAlQAgAjAhAjQAIAJAJAGQAFADAYAKQAZAKAigXQAigXgOg9QgPg9AGgZQAJgqAQgpIgNgrQAbAiAfAgQAiAjAsAXQAUAKAVAHIAIACQAHABAdgDQAcgDAZgKQAZgJANgyIANAyIgcAPIggANQgtARhBARQgVAAglgNQgQgGgNgGQgRgIgNgKIAAAAQgKgtgPgyQAPAyAKAtIAAAAQANAKARAIQAIAjAEBDQAEA2gLA2gAhuGOIgCgCIABgLIAKANgAnxGOQAJgpAOgmIAIgSIATgxIgTAxQgIgBgMgGIgGgEIgGgDQAKgHAGgMIALgXIAIgQIAdg5QAUgoARgpQgRBNgYA+IAAAAIgJAWIAQADQAKAcATAXQADAEAEgCQAGgBADgFQAIgLAGgNQAQghATghIgBACIgDASQgNA9gKAeQgQAsgNAfgAhvGBIAAAAgAmHjVQAKgPAMgeQAJgVAHgUIAAAAQAMgmAFgiQAOAoAQA/IgEACQgbAZgyAhgAg+k9IgBgEQgLgmgPgjIAIgDIACACIAUAUQAnAnAUAxIgCABQgggNgcgSg");
	this.shape_10.setTransform(54,-43.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhuBJIAAABIABABIgEABIADgDgABxg2IgEgEIAFAGIgBgCgABehLIAAAAIABABIgBgBg");
	this.shape_11.setTransform(34.4,-77.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#D2C58E").s().p("ABsG0QgYgKgFgDQgKgGgHgJQghgjghgjIgnglQAFgcAFggIAAgFQAGgvAEg1IAAgBIAAAAIADhCIABgwIABgBQAEgWgFgWQgCg+gNhOIgCgKQgFgYgGgYQAcASAeANIAEgBIACAEIgCgEQgUgxgmgnIgUgUIgBgBIAAAAIgFgGIgQgRIB8hNIACgBQgFgGgEgFIgBgBIgCgCIgCgCIgCgRIgBgDIA/AHQAcAPA0AxIgKAFQgGAEAJABQAYASA+BBQBXBcA0BSQBSCEAUBgIAPBEQgNAygZAJQgZAKgdADQgcADgHgBIgIgCQgVgHgUgKQgtgXgigjQgegggbgiQgNgmgPgpQgIgVgnhUQAnBUAIAVQAPApANAmIANArQgRApgIAqQgGAZAOA9QAPA9gjAXQgXAQgTAAQgJAAgHgDgAARi7IABgBIgBAAIAAABgAB/lIQgQAagaAeQgZAegqA2QAqg2AZgeQAageAQgaQARgaAQgDQgQADgRAagAApmSIAugdIguAdgAmCGRQgUgXgKgcIgPgDIAJgWIAAAAQAYg+AQhNIACgEQAEgRACgRQAJg0AHg8IgDgwIADAwQgHA8gJA0IgIAmQgQApgUAoIgdA5IgIAQIgLAXQgGAMgKAHIgBgBQgJgGgEgGIgBgJIgCg0IgCgiIAAgLIAAgdIAJhxQAFg+ALgrQAUhMA5hLIAYARQgFAJgEAEIANgIQAyghAbgZIAEgBIACAJIACAJIAGAoQAIBFgDBKQgDAQgNBVIgHAuQgMBMgLA3QgTAhgQAhQgGANgIALQgEAFgFABIgDABQgCAAgCgDgAkjitIAAAAQgPg/gOgoIAAAAQAPgJAmgMQAsgOAYgZQACALAAAMIgGBGIAAACQgSAIgdAhIgdAkIAAAAIgMgJg");
	this.shape_12.setTransform(52.5,-52.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#D3BFA5").s().p("AoeIGIAsguQAcgfAkgSQAMAGAHACIgHARQgOAngJApIhgADgAHtIQIgChLIAAhGIAAhKIAggOQAIApAMDAgAinjQIAGhHQABgMgDgKQgDgKgFgIIAcgZIAAAAIAPgKIgDgCQAbgdAagfQAVgYASgaQAQgWAMgXIAIgTIAMAFQgIAegNAcQgRAdgYAYQgjAigoAaQAogaAjgiQAYgYARgdQANgcAIgeIALACQgGAzgLAvIAcgVIgBAkIgJAAQgOAqgeAgQgSASgTAQIgZAVQgbAVgZAXQgJAIgVAXIAAgCg");
	this.shape_13.setTransform(48.8,-56.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#EDE4D8").s().p("AgJAMIAEgMQAEgLAFgFIAGABIgBAHIgBABIgFAYg");
	this.shape_14.setTransform(49.5,-110.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#267D31").s().p("AArAMQgDgKAFgNIAFgLQAKgDAEAQIACAIQAEAWgLACIgEABQgIAAgEgMgAhAARQgCgGAAgJIAAgEIABgGIABgEQADgGADAAQAEAAACAGIACAEIABAGIAAAEQAAAJgDAGQgCAHgEAAQgDAAgDgHg");
	this.shape_15.setTransform(22.8,-121);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FEEED6").s().p("AniJfQBzhUAFAPIAAABIABABIAEAHQAEAGAIAGIACABIAFAEIAHADQgkASgdAfIgrAuIAAANIicAFQA6ghA3gogAGZIzQgFhDgIgjQAOAHAQAGQAkANAVAAQBBgRAugSIgBBLIABBGIACBLIjCAAQAKg3gDg2gAhEgJIgBgCIAFgzQAUgXAKgIQAZgXAYgVIAagVQATgQASgSQAgggANgqIAKAAIAAASIARgIIAPAQIADACIACADIABAAIAHAMIh+BOIAAAAIABABIALAXQAPAkAKAmIABADQAGAYAFAXIgBAAIggAJQhWAAgygVgAiaiqQgRgKgNgOQgbgfgVgjQgZgqgJgvQgJgvAHgxQAFggAAgfQgBgVABgUIAHAAQATgSAagDQgaADgTASIgHgBQADgZAGgYQALgqAWgmIAPAOQAgAeAmAYQAhAWAkARIAIgKQAkAdAnAPIAJgMIA0AcQAUggAXgeQALgOAPgEQAKAFADAKQAFAWgGAWIgFAXQgBAIgCAHQgRAugNAtIgBgCIAAABIgGgBQgHAFgEAMIgEANIgJATQgMAXgPAWQgTAagUAYQgYAfgcAcIADADIgOAKIgZAPIgHAEQgPAJgRAGQgLADgLAAQgPAAgNgHgAh3k1IhTAMIBTgMIBNgPIhNAPgAjIl2QAVAMAaABQgagBgVgMQgIgGAAgHQAAgFADgGIAXgnQANgYABgxQgBAxgNAYIgXAnQgDAGAAAFQAAAHAIAGgAhqoNIgFALQgFAPADAKQAEAOAMgCQALgDgEgYIgCgIQgDgOgJAAIgCABgAjgn5IAAAGQAAAJACAGQADAHADAAQAEAAACgHQADgGAAgJIAAgGIAAgGIAAgEIgDAAQgCgGgEAAQgDAAgDAGIgBAEIgBAAIAAAGgAhhotQAVADAoAMQgogMgVgDQgRgDgOAJQAKgHANAAIAIABg");
	this.shape_16.setTransform(38.6,-70.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#3E3720").s().p("AA7AwIAKBBIgcgIQgrgPglgjIAeA6QkohxB2gsIAKAFIgKgQIABgFIBaAHIgvgTQADgEAEgEQAHgFAHACQAfABAgAEIhBgeIAogGQAogDAjAUIgjgcQBJABA/AoIgIALQAdAJAUASQBCA6AXBgQgIgCgIgFQgOgJgHgPQgIgQgPgDIAFBEQg9gcgvgyg");
	this.shape_17.setTransform(38.2,-147.3);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#282415").s().p("AC4FBIANgEIAAADIACARgACnE3IABgkIgdAVQAMgvAFgzQACgPgDgOIgBgGQANgtARguQACgHABgIIAFgXQAGgWgFgUQgDgKgKgFQgPAEgLAOQgXAcgUAgIg0gcIgDgCIgagOIgFgFIAFAFIAUAcQgpgPgigbQgNgLgNgOIASAhQgkgPghgWQgmgYgggeIgPgOIAEgFIgEAFIgMgPQgRgWgMgYQAMAYARAWIAMAPQgWAmgLAqQgGAWgDAZIAAABQgBAUABAVQgcgngLguQgLgvADgwQABgiALgfQAIgYASgUQAJgLAOgCQAmg+BFgVIAogNQAcgIAcABQBUABBPAhQAPAGAOAJQAcAQAUAYQAWAYAMAfQARAtgCAxIgBApQgBAcgEAZQgIA4gYA0QgKAVgIAXQgPArgLAtQgEAQAAASQABAYAFAXIgNAEIgRAIgADFg7IgFhEQAQADAHAQQAIAPANAJQAJAFAHACQgWhhhCg7QgVgTgcgIIAHgLQg/gohIgBIAhAcQghgUgoADIgoAGIBBAeQgggEgggBQgHgCgGAFQgFAEgDAEIAvATIhagHIAAAEIAKAQIgLgEQh1AuEmBxIgcg6QAiAjAuAPIAcAIIgKhBQAuAyA9AcgADFE9IAAAAgAi7hkIAAAAg");
	this.shape_18.setTransform(35.2,-128.6);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f().s("#35301C").ss(1,1,1).p("AiAACQAwgyA8AbAASAXQAkgPBLAX");
	this.shape_19.setTransform(29.5,-127.9);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f().s("#FF0000").ss(1,1,1,3,true).p("AAAACQAAgCAAgB");
	this.shape_20.setTransform(49.3,-73);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f().s("#000000").ss(1,1,1).p("AEmmrQgEAFgFAGQBKAwBXBqQBXBpAtBxQAnBhAaBeQADANAEANQgKALgNAJQAAAJAJDYQABAFAAAFAElmsQhXg8gHgHQgTANgRALQgYARgUANQgwAggbALQAAAAgBAAQAAAAgBABIgBAAQAAAAgBAAQgIADgFACQgBAAgCAAIACAAIABAAIAPACQABAAAAAAQABAAAAAAQABAAAAAAQAlgEBACdQAhggAcgtQAZgoA1g+AElmsQABAAABABIgBAAACHn7QADALAZAZAg+kzQgEAXgJAZQABAAAAABQAWANAhAAQBUAAAigXQgDgJgCgJABckkQgSg5gegkABtBeIAFgcQAFgZAAgoIAAhBQAAh6gUhSAg+mrQgBACgBABQAAAAgBABQgBAAgBABQgBAAgBAAQAEAPACAOQAEAZAAAXQAAASgDAUAg+kzIAAAAQgbAghBAtQAIAXACAmQADApgDA7QgGBwgRB7QgGApgKAsQgCAIgCAIAg/mJQgeARhaAkQAIAOAIA1QABAEAEAOQAEAKAEAPAi3lUQgEAigOApIAAAAIAAABQgMArghAzQAFAJBPheAjJkJQgRAHgJAKQg6BAgeBCQguBigPCZIAACbQAAABABAAQAIAIARAOQAHAGAHAEQANAHAMABAkECiQAJgiAGgfQAQhWgChJAhTGiIB0AAQAFgeAPg4QAUhIAJghQAGgXABgGIAUhoAklEQQgIAZgKAgQgFAOgFAPQgKAggHAcIBoAAQAdhPAShIAklEQQAIgYAFgRQAMgkAIghAl4EgIAAADQjRB6hABfQBTgDA6gGQAFgBAEAAAnyHyQA5gHAhgKQAjgLAagLQAEgUAFgVIgYAAAjqGiQgEAJgDAJAhTGiIiXAAAFNB0QAHAVAHAZQAPArASAPQAGAGAJAFIABAAQARAHAbAAQA/AAA6gQQAOgFANgEAJNDUQAWgIAQgLAE7A6QgBgBAAgCQgahRgkhPAE7A6QAIAaAKAgAGMDnQAMAngNCKIAAAKIC8AAIA1AAAAhGiIFqAAIAAAZAlbHLIAAAAQgCANgCALAAhGiQgDARgBAIAnyHyQgBAAAAAA");
	this.shape_21.setTransform(39.9,-44);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f().s("#000000").ss(1,1,1).p("Aizk1QAHgBAHAAAizk1IAAAAQgiACgTANQhFBTAEBpQADBjAvA2IABAAQAAABABABQAAAAABABQAAAAAAAAQACACABABQAAgCgBgCQAAgBAAAAQAAgBgBAAIAAgBQAAgBAAAAQgGgcAAgRQAAgSAGgFQAHAGALAPQgBgRACggQAAgBAAAAQAAgCAAgCQADhAAYg9QBAA9AiAdIABAAQAHAGAGAFQAvAlA4AIQgCgFAAgGQgBAAAAgBIgHAAAClEaQAEgFACgEQABgCAAgCIABgBQAJgXAIglQAIgjAKgRQADgGADgFQBUiwAAhMQAAhwhPhJQhShMiIAAQgoAAgyAMQhBAQgZAfAASgjQADABAGgDQgGgFgFgEAjhgCIAAABQAAAKACADQACAFAGAVQACAFABAFQgFAPgEAOQgBAEgBAFQgJAhAFA4QAFA3A4BCQAtA0AdANQAHADAGABQAZADAQABQABAAAAAAQABAAABAAQABAAAAAAQACAAABAAQABgBABAAQASgHAQgMQAEgDAEgDQAVgPAVgUQBOhKAQg9QABgEABgEIgGgaACbCOQADgRAAgSAjfBWQgLgIgHgZQAJANALALAAFAGQgFAAgDAJQgEAJABAMQAAANADADQADADADADQADABACgBQADgBADgDQAFgFAAgNQAAgMgEgJQgDgIgEgBQgBAAgCAAgAiIA5QgEAHgFAAQgEAAgDgHQgCgIgBgNQAAgMADgIQADgIAFgBQAFgBADAJQAEAJAAAMQAAANgEAIgAhVAwQgWBKgbARQgIAOATANQAUANAkABABmgKQgJgEgCgEQgDgFAAgDQAGAGAKAHQAFADAFADQAMAHARAEIgJgJIgCgFIAdATQACgHAGgBQAFgBAEABQAbAAAAA0QAAgKgHAUQgKAigKARQgPAZgCAJIgDAAACaCUIAAABQgBAIgCAIIABAKQAAAzgMAhQAJgUASgMQAAAJgMAXIAAAdQACABADgCAAbglQAOAJAUAJQAaANANABAChAJQAAACAAADQAAAGADgBIAGAAACaCUIAAAAQABgDAAgDACrERIACgDQAAgBAAgBACtEOIACgGIgCAEACkEcQgCABgCACAClEaQAAABgBABAhWELQA3AHBigs");
	this.shape_22.setTransform(36.6,-123.7);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#284360").s().p("AgrEmIAJgIIAQgOQATgQAHgeIAEAEIgEgEIgJgLQgOgLgPgJIgmgVIglgUQgUgKgXgBIAEgQQALgrAFgqQASh5AFhxQADg8gCgpQAFADACAEQAPAXAFAbIAEAhQABAPgBAQIgDAeQgEAaAGAaQAGAdAaALQANAFANAEIAfAHQAdAFBpABIgUBmIgHAdIgdBpQgPA4gGAeg");
	this.shape_23.setTransform(36,-31.6);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#3A5F87").s().p("AiwFrQAdhPAShIQAXABAUAKIAkAUIAnAVQANAJANALIAMALIgBAAQgHAegTAQIgQAOIgJAIgAAiAhIgigHQgLgEgMgFQgagLgHgbQgGgaAEgaIADgeQACgQgCgPIgEghQgEgbgPgXQgDgEgFgDQgCgmgIgXQBBgsAbghIAAAAQgEAXgJAZIABABQAUANAhAAQBWAAAigXQAUBTAAB5IAABDQAAAogFAXIgFAcQhogBgdgFg");
	this.shape_24.setTransform(34.1,-38.5);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#267D31").s().p("AhNAdQgEAAgDgIQgCgIAAgMQgBgLADgIQADgHAFgBQAFgBAEAJQADAIAAALQAAAMgEAIQgEAIgFAAIAAAAgABHAWQgFgCgDgDQgDgEAAgMQAAgLADgJQAFgJAGAAIACABQAEABADAHQAEAJAAALQAAAMgFAGQgDADgCABIgCAAIgEgBg");
	this.shape_25.setTransform(29.8,-120.1);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#968150").s().p("Ah4GVQAFgeAPg4IAdhqIAvAxQARASARARQATARAGALQAHALAgAQQAbAOAYgJIAJgCIAJgEIAIgHQAGgFAEgGQAOgSACgWQADgfgHgPIgHgSIgJgtQADgkASguIgTg5QAYAIAGAIIAcAnQAQAVAUATQATASAWANQAPAJARAEQAMADA6gDQA5gEAiguIAHAaQgJALgNAJQgQAKgWAJIgBAAIgbAKQg6AQhAAAQgaAAgSgIIAAAAQgJgEgHgGQgRgPgPgrIgOgvIAOAvQAPArARAPQAHAGAJAEIAAAAQAMAogNCKIAAAKgAntGVQAHgcAKggIAJgdIATg5IgTA5QgLgBgNgHQAPgSAJgVIARgnIAUgvIAPgiQgIAhgMAkIgNApQAMAHAFAKQAIAPAQAJQAKAGALAAQAEAAAEgCQAFgBAjhBIgEAQQgSBIgdBPgAmRi3QAggzANgsIAAAAIAAAAQAOgpAEgiQAIAOAIA1IAFASQhIBWgLAAIgBgBgAgckEIgfgnIgCgGQgSg6gegjIgBgFIABAAIABAAQAkgEBBCdQgQgDgFgHg");
	this.shape_26.setTransform(55.4,-42.7);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#D2C58E").s().p("ABhGqQgggQgHgLQgHgLgTgRQgTgRgOgSIgvgxIAHgcIAUhoIAFgcQAFgZAAgoIAAhBQAAh6gVhSIgFgSIAfAnQAFAHAOADQAhggAcgtQAagoA0g+Qg0A+gaAoQgcAtghAgQg+idgkAEIgBAAIgBAAIgCAAIgPgCIAAgBIANgEIACAAIAAAAIACgBIAAAAQAbgLAwggIArgeIAkgYQAHAHBWA8IABABIgJALQBKAwBXBpQBYBqAsBvQAnBjAaBeQgiAug6AEQg5ADgMgDQgRgEgPgJQgXgNgTgSQgTgTgQgVIgdgnQgGgIgXgIIgBgDQgahTgkhNQAkBNAaBTIABADIASA5QgRAugDAkIAIAtIAIASQAGAQgDAeQgCAWgOASQgEAGgFAFIgJAHIgIAEIgJACQgKAEgKAAQgPAAgQgJgAnjF0IgZgWIgBgBIAAibQAPibAuhgQAfhCA5hAQAJgKASgHIAAAAQgNAsghAzQAFAJBQheIAIAZIgIgZIgFgSQgJg1gHgOQBZgkAfgRQAEAZAAAXQAAASgDAUQgcAghAAtQAHAXACAmQADApgDA7QgFBwgSB7QgGApgKAsQgjBBgEABQgEACgFAAQgLAAgKgGQgPgJgJgPQgFgKgLgHIANgpQALgkAJghIAGgQQAKgVACgXQAAgDgEgCQAPhLAAhDIgBgRIABARQAABDgPBLQgGAfgIAiIgPAiIgVAvIgRAnQgJAVgPASIgOgKg");
	this.shape_27.setTransform(53.2,-50.1);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#D3BFA5").s().p("Ao3JAIBGhYQAngxAOgNQAPgNASgIQAAABABAAQAAAAAAAAQAAAAABAAQAAgBABAAIABgBIACgEQANAIAMAAIgKAeQgKAfgHAcIgXAAIAXAAIgJAqQgaALgjALQggAKg6AGgAIDHxQAEgZADgaQACgQAAgQIABghQgBgcgCgbIgDgiIABAAQAWgJAQgKIAKDggAiCjjQADgUAAgSQAAgYgEgYIgGgeIACAAIACgBIABgBIABgCQASgHASgMQAagkAMgNIAXgXIASgTQASgUAMgZQANgaAJgbIAHgVIAGAaIABAJQAAA0gLAhQAIgUASgMQAAAJgMAXIAAAcQACACAEgCIgWAeQgOARgPAQQgQAUgPAaQgKgBgHAHIgCABIACAAIgSASIglAnQgIAIgJAGIgSAOgAAvoeQgQA9hLBJQgWAVgVAPIgIAGIAIgGQAVgPAWgVQBLhJAQg9IACgIIgCAIg");
	this.shape_28.setTransform(46.8,-52);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FEEED6").s().p("AlcIOIABgCIAZAWIAOAKIgDADIgDABQgSAJgPANQgOANgoAxIhFBYIgBABIgIABQg7AGhTAEQBAhgDRh6gAGmKNIAAgKQANiJgLgoQARAIAaAAQBBgBA5gQIAbgJIADAhQACAcAAAcIAAAgQAAARgCAQQgDAZgFAagAgugXIAAgBQAIgYAEgXIAAAAIATgPQAJgGAGgHIAlgoIARgSIABAAIAPADIABgBIABAFQAeAkASA6IACAFIAFASQgiAYhWAAQgfAAgWgOgABpjSQAPgPANgRIAWgfIAEgDIAEAEQADAMAZAZIgsAeQgwAfgbALQAPgbASgUgAgni+IgBAAIgCgBIgBAAQgQAAgZgEQgGgBgIgDQgcgNgtg0Qg5hBgEg4QgFg4AJghIACgIIAJgdIgDgKQgGgVgCgGQgCgDAAgMIAAgBQgBgQACghIAAgBIAAgEQADg/AYg+QBAA9AiAdIABAAIANALQAvAlA4AJQADAAAGgDQANAKAUAJQAbAMANACIABgGQgIgEgCgEQgDgFgBgDQAHAGAKAHIAKAHQALAHASAFIgJgKIgDgGIAeAVQACgGAGgBQAFgCAEACQAbgBgBA0QAAgJgGAUQgKAigKAQQgPAZgCAKIgDAAIgEAAIAAgBIABgGQADgRAAgSQAAASgDARQgDAHgHgKIgIAVQgIAbgNAaQgMAagUATIgSAUIgXAXQgNANgZAjQgRAMgRAHIgDACIgCAAgAhKkkQAyAABPgjIAAAAIAGgDIgGADIAAAAQhPAjgyAAIgCAAIAAAAIgPgBIAPABIAAAAIACAAgAiAmJQAUANAkAAQgkAAgUgNQgOgKAAgKQAAgEADgEQAagQAXhKQgXBKgaAQQgDAEAAAEQAAAKAOAKgAiNn3QAEgIAAgMQAAgNgEgJQgDgIgGABQgFAAgCAIQgDAIAAANQAAAMADAIQACAIAFAAQAFAAAEgIgAgIohQgEAJABANQgBAMADADQADAEAGACQABABACgBQADAAADgDQAFgGAAgMQAAgNgFgJQgCgHgEgCIgDAAIAAAAQgEAAgEAJgACeocIABAAIAGAAIgGAAIgBAAIAAAAIAAAAQgCgBAAgFIAAAAIAAgFIAAAFIAAAAQAAAFACABIAAAAIAAAAgAA0o8IgDgBIgCAAIAAAAIgEgBIAAAAIgCgBQglgKgZAAIgBAAIAAAAQgSAAgOAEIgCABIAAAAIAAAAIACgBQAOgEASAAIAAAAIABAAQAZAAAlAKIACABIAAAAIAEABIAAAAIACAAIADABIAAAAgAjMpYIABgBQAfghAkAAIAAAAIAAAAQATAAAUAJIAAAAIAAAAQgUgJgTAAIAAAAIAAAAQgkAAgfAhIgBABgAj2n6IgBgFIAAgBIgBgBIAAAAIAAgBQgGgcAAgTQAAgTAFgFQAIAHALAOIAAABQAAAMACADQACAGAGAVIADAKIgJAdQgLgLgJgNgAjmo0IAAAAg");
	this.shape_29.setTransform(37.1,-67.5);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#282415").s().p("ACbFIIAAgdQAMgXAAgJQgSAMgJAUQAMggAAg0IgBgJIADgRIAAAAIAEAAIADAAQACgKAPgZQAKgQAKgjQAHgTAAAJQAAg0gbAAQgEgBgFABQgGACgCAGIgdgVIACAFIAJALQgRgFgMgIIgKgGQgKgHgGgGQAAADADAFQACAEAJAEIgCAFQgNgBgagMQgUgJgOgKIgLgGIgBgCIgHAAIAHAAIABACQAAAFACAEQg4gHgvglIgNgLIgBAAQgigdhAg9QgYA+gDA/IAAAEIAAABQgCAfABAQQgLgOgHgHQgGAFAAATQAAATAGAbIAAACIABABIAAABIABAFIgDgDIAAgBIgBgBIgBgBIgBgBQgvg4gDhhQgEhoBFhUQATgNAigCIAAAAIAJAAIADgBIACAAIAAAAIAAAAIgCAAIgDABIgJAAQAZgfBBgPQAygMAogBQCIAABSBNQBPBIAABwQAABLhUCxIgGAMQgKARgIAjQgIAkgJAXIgBACIgBADIgGAJQgDACgCADIgDACIgCgBgADEgIIgEgyIAJgDIA7AUIAGgFQgChag5g6QhGhGhfgaQgYgGgWgEIAeAVQgsgQgyAMQAXAFAQAOIALAJQgcAEgqALQgOAEgOAGQAVgCATAHIAMAGIhSgGIAFARIgQgIIgGACIgGAEIgGAGQAUAhAeAcQBAA7BQAZIgDgNIgBgIIgBgJIABgEIAAgGIAEAGQAoA5BGARIgFgpIAGAFQAQAUAVAMIAdAPg");
	this.shape_30.setTransform(36.6,-127.7);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#3E3720").s().p("AB6CCQgVgMgRgTIgGgFIAFApQhFgRgmg5IgEgGIgBAGIAAAEIAAAIIACAIIADAOQhTgZg/g7QgegbgUggIAGgGIAFgEIAHgCIAQAIIgFgRIBSAGIgMgGQgTgIgVADQANgGAPgFQAqgLAcgDIgLgKQgQgOgXgFQAygLAuAQIgggWQAYAEAYAHQBdAaBGBGQA5A4ACBaIgGAFIg7gUIgJADIAEAyIgdgQg");
	this.shape_31.setTransform(41.1,-143.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2}]}).to({state:[{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19}]},3).wait(37));

	// Layer 2
	this.instance_2 = new lib.gchair("synched",0);
	this.instance_2.setTransform(41.6,45.4,1,1,0,0,0,78,109.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2}]}).wait(40));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-142,-162.4,291.1,338.5);


(lib.jakechairexit = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// Layer 9 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("EgWuAh/IDdi5QACAZAcAAMAlMAAAMglMAAAQgcAAgCgZIAAgFMAAAhAhQAAgeAeAAMAocAAAQAeAAAAAeMAAoA7XIkWFoIggAoIAggoIAIAAIh5Cgg");
	mask.setTransform(123.1,217.5);

	// Layer 10
	this.instance = new lib.gjakeexitfloor("synched",0);
	this.instance.setTransform(406.2,409.1);

	this.instance.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({startPosition:0},21).to({x:122.1},19,cjs.Ease.get(1)).wait(20));

	// Layer 7
	/* Layers with classic tweens must contain only a single symbol instance. */

	// Layer 8
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#A2A2A2","#52482C"],[0.004,1],2.4,2.3,18.8,18.8).s().p("AkwEAIJhn/IAAH/g");
	this.shape.setTransform(8.1,409.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#52482C","#A2A2A2"],[0,1],-30.5,20.6,-30.5,-23.9).s().p("Ax9EEIAAn/IAJgIMAjxAAAImGIHg");
	this.shape_1.setTransform(153.7,409.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_1},{t:this.shape}]},5).wait(55));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(96,352.7,861.9,491.5);

})(lib = lib||{}, images = images||{}, createjs = createjs||{});
var lib, images, createjs;